### ISSUE TITLE
Open Graph

### ISSUE THREAD

**Issue by mvondracek** [dusekdan/YourExpirationDate#2]
Hi @dusekdan and @popanda , I like the idea of your project and I wanted to share it on social networks. :) Just a suggestion, it's a pity it does not have open graph information for better sharing on social networks.

**Comment by dusekdan** [comment]
Hello @mvondracek! 

I did plan on eventually adding something like that. Your issue inspired me to speed things up.

I added a few basic og: meta tags as you can see in the linked commit, but when I debug it in Facebook OG debugger, it significantly reduces the linked `og:image`'s quality.

[Address the og:image is pointing at](https://i.imgur.com/PpsxtYu.png) VS [how OG debugger sees it](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fdusekdan.github.io%2FYourExpirationDate%2F). 

Do you have any experience/recommendation for me here?

**Comment by mvondracek** [comment]
Hi, I don't see much difference between those two images... Have you fixed it already?

**Comment by dusekdan** [comment]
I suspect that FB debugger originally scraped lower quality image and cached it for a while, which is why I was asking for assistance. Now the pictures are almost identical. So all is good now.
